language: go

go:
  - 1.12.x
  - 1.13.x
  - 1.14.x

os:
  - linux

before_install:
  - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.32.2

script:
  - export GO111MODULE=on
  - go get -d -t ./...
  - go mod download
  - go vet ./...
  - go test ./...
  - golangci-lint run